### PR TITLE
create a plfash image to store nvram

### PR DESCRIPTION
**Pull request by ubenmackin**
Rudimentary nvram file creation. To solve #7.

Checks if there is a file called DISK_IMAGE.nvram. If it doesn't exist, create it using the included qemu-img. If it does exist, just continue on.

### CODE REVIEW

**Comment by shareefalis** [comment]
It is a good short solution considering we don't have a VM manager

**Comment by ubenmackin** [comment]
Ya, that was my thought. Ideally, we can get to a VM Manager, and house multiple configs. If I get some time, I might poke around and see what I can do. I'm not a Swift programer by trade, but wouldn't mind trying to learn.

**Comment by conath** [comment]
Just a heads up: there's already lots of work going into a modern iOS & macOS QEMU VM manager called [UTM](https://github.com/utmapp/UTM) by @osy and contributors. The latest 2.0.14 it supports the macOS Hypervisor framework for speedy VMs.

**Comment by KhaosT** [comment]
Thanks ^^

**Pull request merged**
